sudo: required

language: java

services:
  - docker

script:
 - docker build -t plaguedocktor/hybris-core-trial .
 - docker ps -a
 
after_success:
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push plaguedocktor/hybris-core-trial;
