sudo: required

language: java

services:
  - docker

script:
 - docker build -t plaguedocktor/hybris-core-trial .
 - docker ps -a
 
deploy:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"