sudo: required

language: java

services:
  - docker

script:
 - docker build -t plaguedocktor/hybris-core-trial .
 - docker ps -a
 
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi