server:
  build: .
  links:
    - hybris-mysql
  ports:
    - "9001:9001"  
hybris-mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: nimda
    MYSQL_DATABASE: coretraildb