hybris-server:
  build: .
  links:
    - hybris-database
  ports:
    - "9001:9001"  
hybris-database:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: nimda
    MYSQL_DATABASE: coretrialdb